
### Add new artist
POST http://localhost:3003/api/profiles/artists
Content-Type: application/json

{
    "username": "Artist with description",
    "password": "test",
    "name": "Uniikki",
    "address": "test address",
    "postalCode": "12345",
    "city": "Pori",
    "country": "Finland",
    "email": "test@test.fi",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dignissim diam leo, eu aliquam purus rutrum at. Mauris tempor non elit ullamcorper posuere. Curabitur sit amet bibendum urna, ut dignissim ligula. Nullam pellentesque rutrum imperdiet. Cras massa nunc, aliquam ac mattis quis, suscipit eget nulla.",
    "images": [
        "https://source.unsplash.com/random/1080x1080",
        "https://source.unsplash.com/random/1080x1080"
    ],
    "tags": ["uniikki"]
}
### Edit artist

PUT http://localhost:3003/api/profiles/artists/5cab2b0c70f3fd6420126d03
Content-Type: application/json

{
    "username": "Pekka",
    "password": "test",
    "name": "Artisti pekka päivitetty",
    "address": "test address",
    "postalCode": "12345",
    "city": "Göteborg",
    "country": "Sweden",
    "email": "test@test.fi",
    "images": [
        "https://source.unsplash.com/random/1080x1080",
        "https://source.unsplash.com/random/1080x1080"
    ],
    "tags": ["testTag", "testTag2"]
}
### Remove artist

DELETE http://localhost:3003/api/profiles/artists/5cab2a00532b825e140d783a
Content-Type: application/json

###