
### Add new studio
POST http://localhost:3003/api/profiles/studios
Content-Type: application/json

{
    "username": "testStudio",
    "password": "test",
    "name": "Pekan Studio",
    "address": "test address",
    "postalCode": "12345",
    "city": "Göteborg",
    "country": "Sweden",
    "email": "test@test.fi",
    "images": [
        "https://source.unsplash.com/random/1080x1080",
        "https://source.unsplash.com/random/1080x1080"
    ],
    "tags": ["wifi", "computers"]
}
### Edit studio

PUT http://localhost:3003/api/profiles/studios/5cab2339e320fa26c8701685
Content-Type: application/json

{
    "username": "Pekka",
    "password": "test",
    "name": "Pekan studio päivitetty",
    "address": "test address",
    "postalCode": "12345",
    "city": "Göteborg",
    "country": "Sweden",
    "email": "test@test.fi",
    "images": [
        "https://source.unsplash.com/random/1080x1080",
        "https://source.unsplash.com/random/1080x1080"
    ],
    "tags": ["testTag", "testTag2"]
}
### Remove studio

DELETE http://localhost:3003/api/profiles/studios/5cab2339e320fa26c8701685
Content-Type: application/json

###